---
name: Nginx Proxy Manager
version: dev
slug: nginxproxymanager
description: Manage Nginx proxy hosts with a simple, powerful interface
url: https://github.com/hassio-addons/addon-nginx-proxy-manager
codenotary: codenotary@frenck.dev
webui: http://[HOST]:[PORT:81]
startup: services
init: false
arch:
  - aarch64
  - amd64
  - armv7
hassio_api: true
ports:
  80/tcp: 80
  81/tcp: 81
  443/tcp: 443
  7359/udp: 7359
  8096/tcp: 8096
  8920/tcp: 8920
map:
  - addon_config:rw
backup_exclude:
  - "*/logs"
image: ghcr.io/mackandelius/nginxproxymanager/{arch}
